"""ABIDE I/II resting-state fMRI study definitions for TRIBE v2.

ABIDE (Autism Brain Imaging Data Exchange) provides resting-state fMRI
from ASD and typically-developing (TD) subjects across multiple sites.

Since ABIDE is resting-state (no stimulus), it cannot be used directly
with TRIBE v2's stimulus-to-brain pipeline. Instead, this study class
is used for:
1. Surface projection to fsaverage5 (shared space with TRIBE v2)
2. Functional connectivity analysis
3. Comparing resting-state patterns against TRIBE v2 predictions
"""

import logging
import typing as tp
from pathlib import Path

import numpy as np
import pandas as pd
from neuralset.events import study

logger = logging.getLogger(__name__)

# Sites reserved for held-out testing (cross-site generalization)
_TEST_SITES = {"YALE", "STANFORD"}
_VAL_SITES = {"LEUVEN", "UCLA"}


class AbideRestingState(study.Study):
    """ABIDE I resting-state fMRI study.

    This loads preprocessed ABIDE I data (C-PAC pipeline) downloaded
    via nilearn's fetch_abide_pcp(). Data is in MNI152 volumetric space
    and can be projected to fsaverage5 via TribeSurfaceProjector.

    Note: This study does NOT produce stimulus events (Video/Audio/Word).
    It produces only Fmri events for resting-state analysis.
    """

    device: tp.ClassVar[str] = "Fmri"
    licence: tp.ClassVar[str] = "CC-BY-NC-SA 3.0"
    url: tp.ClassVar[str] = "http://fcon_1000.projects.nitrc.org/indi/abide/"

    _info: tp.ClassVar[study.StudyInfo] = study.StudyInfo(
        num_timelines=1112,
        num_subjects=1112,
        num_events_in_query=1112,
        event_types_in_query={"Fmri"},
        data_shape=(61, 73, 61, 196),
        frequency=0.5,
        fmri_spaces=("MNI152NLin6Asym",),
    )

    def _download(self) -> None:
        raise NotImplementedError(
            "Use AbideDownloader.download_abide1() to download."
        )

    def _get_phenotypic(self) -> pd.DataFrame:
        """Load phenotypic CSV generated by AbideDownloader."""
        csv_path = self.path / "abide1_phenotypic.csv"
        if csv_path.exists():
            return pd.read_csv(csv_path)
        # Fallback: look in standard nilearn download location
        csv_path = self.path / "ABIDE_pcp" / "Phenotypic_V1_0b_preprocessed1.csv"
        if csv_path.exists():
            return pd.read_csv(csv_path)
        raise FileNotFoundError(
            f"Phenotypic data not found. Run AbideDownloader.download_abide1() first."
        )

    def iter_timelines(self) -> tp.Iterator[dict[str, tp.Any]]:
        phenotypic = self._get_phenotypic()

        for _, row in phenotypic.iterrows():
            func_path = row.get("func_preproc_path")
            if func_path is None or not Path(func_path).exists():
                continue

            subject_id = str(row.get("SUB_ID", row.name))
            site = str(row.get("SITE_ID", "unknown"))
            diagnosis = "ASD" if row.get("DX_GROUP") == 1 else "TD"
            age = float(row.get("AGE_AT_SCAN", 0))
            sex = str(row.get("SEX", "unknown"))

            yield dict(
                subject=f"abide_{subject_id}",
                site=site,
                diagnosis=diagnosis,
                age=age,
                sex=sex,
                func_path=func_path,
            )

    def _get_split(self, timeline: dict[str, tp.Any]) -> str:
        """Assign train/val/test split based on acquisition site."""
        site = timeline["site"]
        if site in _TEST_SITES:
            return "test"
        elif site in _VAL_SITES:
            return "val"
        return "train"

    def _load_timeline_events(self, timeline: dict[str, tp.Any]) -> pd.DataFrame:
        import nibabel

        func_path = Path(timeline["func_path"])
        nii: tp.Any = nibabel.load(func_path, mmap=True)

        # Determine TR from header or use common default
        tr = float(nii.header.get_zooms()[-1]) if len(nii.header.get_zooms()) >= 4 else 2.0
        if tr > 10:
            # Header stores TR in ms
            tr = tr / 1000.0
        freq = 1.0 / tr
        n_volumes = nii.shape[-1]
        dur = n_volumes * tr

        events = [
            dict(
                type="Fmri",
                start=0,
                filepath=str(func_path),
                frequency=freq,
                duration=dur,
            )
        ]

        df = pd.DataFrame(events)
        df["split"] = self._get_split(timeline)
        df["diagnosis"] = timeline["diagnosis"]
        df["site"] = timeline["site"]
        df["age"] = timeline["age"]
        return df
